name: "Commit Lint"

description: "Commit Lint Changes"

inputs:
  iam-role:
    description: IAM role arn to assume.
    required: true
    type: string

  session-name:
    description: Optional Session Name.
    required: false
    default: "GithubActions"
    type: string

  aws-region:
    description: AWS Region.
    required: false
    default: "us-east-1"
    type: string

runs:
  using: "composite"
  steps:
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort'
      # # - name: Push changes
      # # uses: ad-m/github-push-action@v0.5.0
      # with:
      #   github_token: ${{ secrets.GITHUB_TOKEN }}
