name: "Cache Dependencies"

description: "Setup Python with pip Cache and Install Dependencies"

inputs:
  iam-role:
    description: IAM role arn to assume.
    required: true
    type: string

  session-name:
    description: "[Optional] Session Name".
    required: false
    default: "GithubActions"
    type: string

  aws-region:
    description: AWS Region.
    required: false
    default: "us-east-1"
    type: string

  context:
    description: Docker build context.
    required: true
    type: string

  dockerfile:
    description: Dockerfile path.
    required: true
    type: string

  image-tag:
    description: Image registry with tag.
    required: true
    type: string


runs:
  using: "composite"
  steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ inputs.iam-role }}
        role-session-name: ${{ inputs.session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-Buildx-action@v2
      id: buildx

    - name: Create Git & SSH Config Dir
      env:
        CONFIG_DIR: "config"
      id: config-dir
      run: |
        mkdir ${CONFIG_DIR}
        cp -r ~/.gitconfig  ~/.ssh ${CONFIG_DIR}/
        echo dir=${CONFIG_DIR} >> GITHUB_OUTPUT
      working-directory: ${{ inputs.context }}

    - name: Build & Push Image
      id: build-image
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        build-args: |
          CONFIG_DIR: ${{ steps.config-dir.outputs.dir }}
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image-tag }}
        push: True


