[tool.pylint.format]
max-line-length = "88"

[tool.bandit]
exclude_dirs = ["tests"]
tests = ["B201", "B301"]
skips = ["B101", "B601"]

[tool.isort]
skip = [".gitginore", ".dockerignore"]
profile = "black"
