name: Deployment Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Integration Workflow]
    types: [completed]
    branches: [main]
  push:
    branches: [main]
    paths:
      - "src/**"

jobs:
  Deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Deploy Keys
        uses: CristovamSilva/ssh-agent-action@master
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY }}

      - name: Prepare Build Context
        run: |
          mkdir root-config
          cp -r ~/.gitconfig  ~/.ssh root-config/
        working-directory: ${{ needs.Config.outputs.context }}

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/deploy
        with:
          docker-context: src
          dockerfile: Dockerfile
          ecr-repository: template
          ecr-push-image: false
          task-definition: template
          task-container: template
          ecs-cluster: template
          ecs-service: template-service
          aws-iam-role: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-1
