name: Deployment Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Integration Workflow]
    types: [completed]
    branches: [main]
  push:
    branches: [main]
    paths:
      - "src/**"

jobs:
  Deploy:
    # if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Deploy Keys
        uses: CristovamSilva/ssh-agent-action@master
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY }}

      - name: Prepare Build Context
        run: |
          mkdir root-config
          cp -r ~/.gitconfig  ~/.ssh root-config/
        working-directory: src

      - name: Build and Deploy to ECS
        uses: CristovamSilva/deploy-to-ecs-action@master
        with:
          docker-context: src
          # dockerfile: Dockerfile
          ecr-repository: gha-test-repo
          ecr-push-image: true
          task-definition: template-task
          task-container: template
          ecs-cluster: default
          ecs-service: template-service
          ecs-deploy: false
          aws-iam-role: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-1

  Report:
    if: github.event.workflow_run.conclusion == 'fail'
    runs-on: ubuntu-latest
    steps:
      - name: Report Failure
        run: echo "Integration Failed"
