name: Deployment Workflow

on:
  push:
    branches: [main]

jobs:
  Config:
    runs-on: ubuntu-latest
    env:
      CONTEXT: ./src
      ECR_REPOSITORY: gha-test-repo
      IMAGE_TAG: ${{ github.sha }}
      CONTAINER: template
      TASK_DEFINITION: template-task
      SERVICE: template-service
      CLUSTER: default
    outputs:
      context: ${{ steps.context.outputs.context }}
      tag: ${{ steps.image-tag.outputs.tag }}
      container: ${{ steps.container.outputs.container }}
      task-definition: ${{ steps.task-def.outputs.task-def }}
      service: ${{ steps.service.outputs.service }}
      cluster: ${{ steps.cluster.outputs.cluster }}
    steps:
      - name: Set Context Directory
        id: context
        run: echo context=$CONTEXT >> $GITHUB_OUTPUT

      - name: Set Image Tag
        id: image-tag
        run: echo tag=$ECR_REPOSITORY:$IMAGE_TAG >> $GITHUB_OUTPUT

      - name: Set Task Definition Family
        id: task-def
        run: echo task-def=$TASK_DEFINITION >> $GITHUB_OUTPUT

      - name: Set Contaienr
        id: container
        run: echo container=$CONTAINER >> $GITHUB_OUTPUT

      - name: Set Service
        id: service
        run: echo service=$SERVICE >> $GITHUB_OUTPUT

      - name: Set Cluster
        id: cluster
        run: echo cluster=$CLUSTER >> $GITHUB_OUTPUT

  Deploy:
    needs: [Config]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # - name: Setup Deploy Keys
      #   uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     ssh-private-key: |
      #       ${{ secrets.GHA_WF_KEY }}
      #       ${{ secrets.DOCKER_DEMO_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update image on ECR
        uses: ./.github/actions/deploy-ecr
        with:
          iam-role: ${{ secrets.IAM_ROLE }}
          context: ${{ needs.Config.outputs.context }}
          dockerfile: ${{ needs.Config.outputs.context }}/Dockerfile
          image-tag: ${{ needs.Config.outputs.tag }}

      - name: Download Task Definition
        run: |
          aws ecs describe-task-definition \
          --task-definition ${{ needs.Config.outputs.task-definition }} \
          --query taskDefinition > task-definition.json

      - name: Update Task Definition
        id: container1
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ needs.Config.outputs.container }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ needs.Config.outputs.tag }}

      # - name: Update Second Container
      #   id: container2
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: ${{ steps.container1.outputs.task-definition }}
      #     container-name: container2
      #     image: ${{ steps.login-ecr.outputs.registry }}/${{ needs.Config.outputs.tag }}2

      # - name: Deploy Task Definition
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: ${{ steps.container1.outputs.task-definition }}
      #     service: ${{ needs.Config.outputs.service }}
      #     cluster: ${{ needs.Config.outputs.cluster }}
      #     wait-for-service-stability: false
