name: Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@master
        with:
          dependencies-directory: src
          application: true
          quality: true
          security: true
          test: true

  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    outputs:
      execution-report: pytest-exec-results
      coverage-report: pytest-cov-results
    steps:
      - name: Test Package
        uses: TeiaLabs/pytest-action@main
        with:
          dependencies-directory: ${{ needs.Build.outputs.dependencies-directory }}
          tests-directory: tests
          package-directory: test_api
          ignore-errors: false
          execution-report: api.xml
          coverage-report-type: xml
          coverage-report: api.xml
  Verify:
    needs: [Build]
    uses: CristovamSilva/gha-workflows/.github/workflows/reusable-integration.yml@main
    with:
      dependencies-directory: src
      source-directory: src
      package-directory: .

      enable-security: true
      security-bandit: true
      security-dependencies-review: false

      enable-quality: true
      quality-sort: true
      quality-format: true
      quality-mypy: false
      quality-flake8: true
      quality-pylint: false

      enable-sonar: false
      execution-report: ${{ needs.test.outputs.execution-report }}
      coverage-report: ${{ needs.test.outputs.coverage-report }}
