name: Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@master
        with:
          dependencies-directory: src
          application: true
          quality: true
          security: true
          test: true

  # Test:
  #   needs: [Build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Test with Pytest
  #       uses: cristovamsilva/pytest-action@main
  #       with:
  #         dependencies-directory: src
  #         tests-directory: src
  #         package-directory: .

  # Verify:
  # needs: [Build]
  # uses: TeiaLabs/gha-workflows/.github/workflows/reusable-release.yml@main
  # with:
  #   dependencies-directory: src
  #   source-directory: src
  #   package-directory: .
