name: Release Workflow

on:
  push:
    tags:
      - "v.*.*.*"

jobs:
  Verify:
    uses: TeiaLabs/gha-workflows/.github/workflows/reusable-release.yml@main
    with:
      dependencies-directory: ${{ needs.Build.outputs.dependencies-directory }}
      source-directory: src
      module-directory: .
